# Default values for chkk-cluster-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: public.ecr.aws/chkk/cluster-agent
  tag: v0.1.7
  pullPolicy: IfNotPresent

manager:
  image:
    repository: public.ecr.aws/chkk/cluster-agent-manager
    tag: v0.1.7
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi

secret:
  chkkAccessToken: CHKK-ACCESS-TOKEN

cronjob:
  schedule: "0 */12 * * *"

config:
  enabled: true
  fileContents:
    rules:
      - exclude:
        - path: $.metadata.name
          match: ^chkk
      - include:
        - path: $.kind
          match: ^DaemonSet|Deployment|Pod|PodTemplate|ReplicationController|StatefulSet$
      - include:
        - path: $.kind
          match: ^NetworkPolicy|CronJob|Namespace|Service|Job|Ingress|Node$
      - include:
        - path: $.kind
          match: ^CSIStorageCapacity|PriorityLevelConfiguration|HorizontalPodAutoscaler|EndpointSlice$
      - include:
        - path: $.kind
          match: ^PodDisruptionBudget|PodSecurityPolicy|RuntimeClass|ValidatingWebhookConfiguration|CustomResourceDefinition$
      - include:
        - path: $.kind
          match: ^TokenReview|LocalSubjectAccessReview|SelfSubjectAccessReview|CertificateSigningRequest|Lease|ClusterRole$
      - include:
        - path: $.kind
          match: ^ClusterRoleBinding|Role|RoleBinding|Ingress|IngressClass|PriorityClass$
      - include:
        - path: $.kind
          match: ^CSIDriver|CSINode|StorageClass|VolumeAttachment$
      - include:
        - path: $.kind
          match: ^ValidatingAdmissionPolicy|MutatingWebhookConfiguration|ControllerRevision$
      - include:
        - path: $.kind
          match: ^PodSchedulingContext|ResourceClaim|ResourceClaimTemplate|ResourceClass$
      - include:
        - path: $.kind
          match: ^PersistentVolumeClaim|PersistentVolume|ClusterTrustBundle|LimitRange$
      - include:
        - path: $.kind
          match: ^ResourceQuota|IPAddress|ComponentStatus|ClusterCIDR|ValidatingAdmissionPolicyBindingList$
      - include:
        - path: $.kind
          match: ^ConfigMap$
        - path: $.metadata.name
          match: ^*dns*$
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
