{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chkk-cluster-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "chkk-cluster-agent.labels" . | indent 4 }}
data:
  clusterguard.config: |
{{ toYaml .Values.config.fileContents | indent 4 }}
{{- end -}} 
