apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "chkk-cluster-agent.fullname" . }}-role
  labels:
{{ include "chkk-cluster-agent.labels" . | indent 4 }}
  annotations:
{{ include "chkk-cluster-agent.annotations" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: [namespaces, limitranges, resourcequotas, componentstatuses]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods, podtemplates, replicationcontrollers, services]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [nodes, persistentvolumeclaims, persistentvolumes]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, list, watch]
  - apiGroups: [apps]
    resources: [replicasets, statefulsets, daemonsets, deployments, controllerrevisions]
    verbs: [get, list, watch]
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch, create]
  - apiGroups: ["networking.k8s.io"]
    resources: [networkpolicies, ingresses, ingressclasses, ipaddresses, clustercidrs]
    verbs: [get, list, watch]
  - apiGroups: ["storage.k8s.io"]
    resources: [csistoragecapacities, csidrivers, csinodes, storageclasses, volumeattachments]
    verbs: [get, list, watch]
  - apiGroups: ["flowcontrol.apiserver.k8s.io"]
    resources: [flowschemas, prioritylevelconfigurations]
    verbs: [get, list, watch]
  - apiGroups: ["autoscaling"]
    resources: [horizontalpodautoscalers]
    verbs: [get, list, watch]
  - apiGroups: ["extensions"]
    resources: [daemonsets, deployments, replicasets, statefulsets, networkpolicies, podsecuritypolicies, ingresses]
    verbs: [get, list, watch]
  - apiGroups: ["discovery.k8s.io"]
    resources: [endpointslices]
    verbs: [get, list, watch]
  - apiGroups: ["events.k8s.io"]
    resources: [events]
    verbs: [get, list, watch]
  - apiGroups: ["policy"]
    resources: [poddisruptionbudgets, podsecuritypolicies]
    verbs: [get, list, watch]
  - apiGroups: ["node.k8s.io"]
    resources: [runtimeclasses]
    verbs: [get, list, watch]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: [validatingwebhookconfigurations, validatingadmissionpolicies, mutatingwebhookconfigurations, validatingadmissionpolicybindings]
    verbs: [get, list, watch]
  - apiGroups: ["certificates.k8s.io"]
    resources: [certificatesigningrequests, clustertrustbundles]
    verbs: [get, list, watch]
  - apiGroups: ["coordination.k8s.io"]
    resources: [leases]
    verbs: [get, list, watch]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: [clusterroles, clusterrolebindings, roles, rolebindings]
    verbs: [get, list, watch]
  - apiGroups: ["scheduling.k8s.io"]
    resources: [priorityclasses]
    verbs: [get, list, watch]
  - apiGroups: ["resource.k8s.io"]
    resources: [podschedulingcontexts, resourceclaims, resourceclaimtemplates, resourceclasses]
    verbs: [get, list, watch]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "chkk-cluster-agent.fullname" . }}-rolebinding
  labels:
{{ include "chkk-cluster-agent.labels" . | indent 4 }}
  annotations:
{{ include "chkk-cluster-agent.annotations" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "chkk-cluster-agent.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "chkk-cluster-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
