apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chkk-cluster-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "chkk-cluster-agent.labels" . | nindent 4 }}
type: Opaque
data:
  CHKK_ACCESS_TOKEN: {{ .Values.secret.chkkAccessToken | b64enc }}
