apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chkk-cluster-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chkk-cluster-agent.labels" . | nindent 4 }}
  annotations:
{{ include "chkk-cluster-agent.annotations" . | indent 4 }}
