apiVersion: v1
kind: Namespace
metadata:
  name: chkk-system
  annotations:
    chkk.io/name: Cluster Agent
    chkk.io/version: v0.1.2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: chkk-cluster-context-cronjob
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: chkk-cluster-context-cronjob
  annotations:
    chkk.io/name: Cluster Agent
    chkk.io/version: v0.1.2
  name: chkk-cluster-context-cronjob
  namespace: chkk-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: chkk-cluster-context-cronjob
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: chkk-cluster-context-cronjob
  annotations:
    chkk.io/name: Cluster Agent
    chkk.io/version: v0.1.2
  name: chkk-cluster-context-cronjob
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - podtemplates
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
      - statefulsets
      - daemonsets
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csistoragecapacities
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - flowschemas
      - prioritylevelconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
      - networkpolicies
      - podsecuritypolicies
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: chkk-cluster-context-cronjob
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: chkk-cluster-context-cronjob
  annotations:
    chkk.io/name: Cluster Agent
    chkk.io/version: v0.1.2
  name: chkk-cluster-context-cronjob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chkk-cluster-context-cronjob
subjects:
  - kind: ServiceAccount
    name: chkk-cluster-context-cronjob
    namespace: chkk-system
---
apiVersion: v1
data:
  clusterguard.config: |-
    rules:
      - include:
        - path: $.kind
          match: ^DaemonSet|Deployment|Pod|PodTemplate|ReplicationController|StatefulSet$
      - include:
        - path: $.kind
          match: ^NetworkPolicy|CronJob|Namespace|Service|Job|Ingress|Node$
      - include:
        - path: $.kind
          match: ^CSIStorageCapacity|PriorityLevelConfiguration|HorizontalPodAutoscaler|EndpointSlice$
      - include:
        - path: $.kind
          match: ^PodDisruptionBudget|PodSecurityPolicy|RuntimeClass|ValidatingWebhookConfiguration|CustomResourceDefinition$
      - include:
        - path: $.kind
          match: ^TokenReview|LocalSubjectAccessReview|SelfSubjectAccessReview|CertificateSigningRequest|Lease|ClusterRole$
      - include:
        - path: $.kind
          match: ^ClusterRoleBinding|Role|RoleBinding|Ingress|IngressClass|PriorityClass$
      - include:
        - path: $.kind
          match: ^CSIDriver|CSINode|StorageClass|VolumeAttachment$
      - include:
        - path: $.kind
          match: ^ConfigMap$
        - path: $.metadata.name
          match: ^*dns*$
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: chkk-cluster-context-cronjob
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: chkk-cluster-context-cronjob
  annotations:
    chkk.io/name: Cluster Agent
    chkk.io/version: v0.1.2
  name: chkk-cluster-context-cronjob
  namespace: chkk-system
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: chkk-cluster-context-cronjob
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: chkk-cluster-context-cronjob
  annotations:
    chkk.io/name: Cluster Agent
    chkk.io/version: v0.1.2
  name: chkk-cluster-context-cronjob
  namespace: chkk-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/instance: chkk-cronjob
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: chkk-cronjob
    chkk.io/name: chkk-cluster-agent
  annotations:
    chkk.io/name: Cluster Agent
    chkk.io/version: v0.1.2
  name: chkk-cluster-context-cronjob
  namespace: chkk-system
spec:
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/instance: chkk-cronjob
        app.kubernetes.io/name: chkk-cronjob
      annotations:
        chkk.io/name: Cluster Agent
        chkk.io/version: v0.1.2
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: chkk-cronjob
            app.kubernetes.io/name: chkk-cronjob
          annotations:
            chkk.io/name: Cluster Agent
            chkk.io/version: v0.1.2
        spec:
          automountServiceAccountToken: true
          containers:
            - env:
                - name: CHKK_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: CHKK_ACCESS_TOKEN
                      name: chkk-access-token
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: public.ecr.aws/chkk/cluster-agent:v0.1.1
              imagePullPolicy: Always
              name: chkk-cluster-context-cronjob
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 500m
                  memory: 512Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - mountPath: /config
                  name: chkk-cluster-context-cronjob
                  readOnly: true
                - mountPath: /etc/downward
                  name: chkk-cluster-context-cronjob-labels
                  readOnly: true
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 12000
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: chkk-cluster-context-cronjob
          volumes:
            - configMap:
                name: chkk-cluster-context-cronjob
              name: chkk-cluster-context-cronjob
            - downwardAPI:
                items:
                  - fieldRef:
                      fieldPath: metadata.labels
                    path: "labels"
              name: chkk-cluster-context-cronjob-labels
  schedule: 0 */12 * * *
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    chkk.io/name: Cluster Agent
    chkk.io/version: v0.1.2
  labels:
    app.kubernetes.io/instance: chkk-cluster-agent-manager
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: chkk-cluster-agent-manager
  name: chkk-cluster-agent-manager
  namespace: chkk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chkk-cluster-agent-manager
  template:
    metadata:
      annotations:
        chkk.io/name: Cluster Agent
        chkk.io/version: v0.1.2
      labels:
        app.kubernetes.io/name: chkk-cluster-agent-manager
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: CHKK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CHKK_ACCESS_TOKEN
                  name: chkk-access-token
          image: public.ecr.aws/chkk/cluster-agent-manager:v0.1.1
          imagePullPolicy: Always
          name: chkk-cluster-agent-manager
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 12000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: chkk-cluster-context-cronjob
